title: Keshav Dewan # your name (or website title) here
description: |
  <div style="text-align: center;">
    <!-- Logo with circular shape (Image on top) -->
    <img src="/images/KDimage.jpeg?raw=true" alt="Keshav Dewan" style="border-radius: 50%; width: 150px; height: 150px;"/>

    <!-- Title below the image -->
    <h1 style="color: #333333; margin-top: 20px;">Keshav Dewan</h1> <!-- Title -->

    <!-- Subheading below the title -->
    <h3 style="color: #333333; margin-top: 5px;">Transforming Data into Insights</h3> <!-- Subheading -->

    <!-- Key Skills Section -->
    <p style="text-align: center;">
      <strong>Key Skills:</strong> SQL | Power BI | Python | Tableau | Google Data Studio | Advanced Microsoft Office
    </p>
  </div>

# Hide "Hosted on GitHub Pages" in footer
exclude:
  - "README.md"

remote_theme: "pages-themes/minimal@v0.2.0"

plugins:
  - jekyll-remote-theme

google_analytics: "UA-000000-0" # your Google Analytics tracking ID here

# Add custom CSS to hide "Hosted on GitHub Pages" in footer
head:
  - |
    <style>
      footer {
        display: none;
      }
    </style>
