title: Keshav Dewan # your name (or website title) here

description: |
  <div style="text-align: center;">
    <!-- Logo with circular shape (Image on top) -->
    <img src="/images/KDimage.jpeg?raw=true" style="border-radius: 50%; width: 150px; height: 150px;"/>

    <!-- Subheading below the title -->
    <h3 style="color: #333333; margin-top: 5px;">Transforming Data into Insights</h3> <!-- Subheading -->

    <!-- Description text -->
    <p style="color: #333333; font-size: 16px; margin-top: 20px;">
      Hello, I am a Data Analyst with a background in Research, Consulting, and Business Development.
      My transition into Analytics stemmed from a desire to focus on generating insights that drive impactful business decisions.
      I am constantly refining my skills and am always open to feedback. You can explore my latest work on GitHub.
    </p>

    <!-- Key Skills Section -->
    <p style="text-align: center;">
      <strong>Key Skills:</strong> SQL | Power BI | Python | Tableau | Google Data Studio | Advanced Microsoft Office
    </p>
  </div>

remote_theme: "pages-themes/minimal@v0.2.0"

plugins:
  - jekyll-remote-theme


# Add custom CSS to hide "Hosted on GitHub Pages" in footer
head:
  - |
    <style>
      footer {
        display: none;
      }
    </style>
