title: Keshav Dewan # your name (or website title) here
logo: "/images/KDimage.jpeg?raw=true" # your photo (or logo) here
description: |
  <strong><br> Transforming data into insights <br></strong>

  <br>Hello,

  I am a Data & Business Analyst with a background in Research, Consulting, and Business Development.

  
  
  <b>Key Skills: SQL | Power BI | Python | Tableau | Google Data Studio | Advanced Microsoft Office </b>

  <br>


