title: Keshav Dewan # your name (or website title) here
description: |
  <div style="text-align: center;">
    <!-- Logo with circular shape -->
    <img src="/images/KDimage.jpeg?raw=true" alt="Keshav Dewan" style="border-radius: 50%; width: 150px; height: 150px;"/>

    <!-- Name below the logo -->
    <h1>Keshav Dewan</h1>
    <h3>Transforming Data into Insights</h3>
  </div>

  <!-- Introduction and Key Skills Section -->
  <p style="text-align: center;">
    Hello, I am a Data Analyst with a background in Research, Consulting, and Business Development.
    My transition into Analytics stemmed from a desire to focus on generating insights that drive impactful business decisions.
    I am constantly refining my skills and am always open to feedback. You can explore my latest work on GitHub.
  </p>
  
  <!-- Add a gap between the introduction and key skills -->
  <div style="margin-bottom: 20px;"></div>

  <p style="text-align: center;">
    <strong>Key Skills:</strong> SQL | Power BI | Python | Tableau | Google Data Studio | Advanced Microsoft Office
  </p>

# Hide "Hosted on GitHub Pages" in footer
exclude:
  - "README.md"

remote_theme: "pages-themes/minimal@v0.2.0"

plugins:
  - jekyll-remote-theme


